name: Deploy to Airbase
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build --platform linux/amd64 -t hawkergb-playbook:${{ github.sha }} .

      - name: Deploy to Airbase
        run: |
          mkdir -p ~/.local/bin
          curl -fsSL https://console.airbase.tech.gov.sg/dist/install.sh | sh
          echo "${{ secrets.AIRBASE_RC }}" > ~/.airbaserc
          ~/.local/bin/airbase --verbose login --ci -e https://console.airbase.tech.gov.sg
          ~/.local/bin/airbase deploy --ci --image hawkergb-playbook:${{ github.sha }} --yes